# -*- coding: utf-8 -*-asdaфывыфв

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(560, 300))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_polyakov = QtWidgets.QPushButton(self.centralwidget)
        self.Button_polyakov.setGeometry(QtCore.QRect(10, 100, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.Button_polyakov.setFont(font)
        self.Button_polyakov.setObjectName("Button_polyakov")
        self.Button_brainly = QtWidgets.QPushButton(self.centralwidget)
        self.Button_brainly.setGeometry(QtCore.QRect(280, 100, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.Button_brainly.setFont(font)
        self.Button_brainly.setObjectName("Button_brainly")
        self.LineEdit_link = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_link.setGeometry(QtCore.QRect(10, 40, 541, 61))
        self.LineEdit_link.setObjectName("LineEdit_link")
        self.Button_HowTo = QtWidgets.QPushButton(self.centralwidget)
        self.Button_HowTo.setGeometry(QtCore.QRect(0, 280, 75, 23))
        self.Button_HowTo.setObjectName("Button_HowTo")
        self.Button_info = QtWidgets.QPushButton(self.centralwidget)
        self.Button_info.setGeometry(QtCore.QRect(540, 280, 21, 21))
        self.Button_info.setText("")
        self.Button_info.setObjectName("Button_info")
        self.Button_info.setIcon(QtGui.QIcon("info.ico"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "1337iq"))
        self.Button_polyakov.setText(_translate("MainWindow", "Взломать kpolyakov.spb.ru"))
        self.Button_brainly.setText(_translate("MainWindow", "Взломать знания"))
        self.Button_HowTo.setText(_translate("MainWindow", "Как юзать?"))
